### ISSUE TITLE
Question about BDSPlugin

### ISSUE THREAD

**Issue by xPrimeMC** [FuturecraftServer/CSRPlugin#1]
我有一个关于BDSPlugin的问题，我尝试对其进行编译，但是即使使用PDB提取器到标头工具时也存在一些缺少的符号，反正我可以提取linux符号吗？ Windows BDS上可能缺少一些符号。

**Comment by kengwang** [comment]
> 非常抱歉,因为此项目为团队项目导致Github没有发邮件提醒我此Issue

BDSPlugin已经过时,我当时用的是Windows 的 1.14.32.1进行的符号提取和开发. 不过现在已经BDS版本迭代很多次了,可能存在符号的变动和丢失,我也没有精力去写C++版本的了.

**Comment by kengwang** [comment]
如果想要进一步交流可以通过QID来添加我的QQ : kengwang
直接在QQ添加好友处搜索即可
Github貌似不会发这个Issue的邮件通知

**Comment by kengwang** [comment]
Closed
